chore: update codeowners for new team structure
FigureTechnologies/gradle-semver-plugin pull request #119
Opened 2023-09-13 20:52 UTC by leeduan

**Problem:** 

We're updating team organization and codeowners to better match company & team structure

**Solution:**

Update this repo per assignments per [notion docs](https://www.notion.so/figuretech/1be68c6593194b989619f3f9af07b87d?v=ff5860acd9e8441bb374f42f68df7f08)

2023-09-13 20:54 UTC, tcrawford-figure requested changes
Are more people going to be added to the backend-platform-dev-experience team?

2023-09-13 21:00 UTC, leeduan commented
> Are more people going to be added to the backend-platform-dev-experience team?

it's all documented here https://www.notion.so/figuretech/GitHub-Teams-and-Code-Owners-7dd80693c9e84257b4a1ba3e540baae8

2023-09-14 12:31 UTC, scirner22 approved these changes

2023-09-14 12:33 UTC, tcrawford-figure approved these changes

2023-09-14 12:33 UTC, merged